/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jocopa3.blocktopographpc.gui.panels;

import com.jocopa3.blocktopographpc.util.WorldListUtil;
import com.protolambda.blocktopograph.util.io.IOUtil;
import com.protolambda.blocktopograph.world.World;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.LayoutStyle;
import javax.swing.border.EtchedBorder;

/**
 * NOTE: Currently not directly used.
 * @author Matt
 */
public class WorldListCell extends javax.swing.JPanel {

    /**
     * Creates new form test
     */
    public WorldListCell(World world) {
        initComponents();
        
        worldName.setText(world.getWorldDisplayName());
        worldSize.setText(IOUtil.getFileSizeInText(world.worldFolder));
        gamemode.setText(WorldListUtil.getWorldGamemodeText(world));
        lastPlayed.setText(WorldListUtil.getLastPlayedText(world));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        worldName = new JLabel();
        worldSize = new JLabel();
        gamemode = new JLabel();
        lastPlayed = new JLabel();

        setBackground(new Color(255, 255, 255));
        setBorder(BorderFactory.createEtchedBorder(EtchedBorder.RAISED, new Color(204, 204, 204), new Color(153, 153, 153)));

        worldName.setFont(worldName.getFont().deriveFont(worldName.getFont().getStyle() | Font.BOLD, worldName.getFont().getSize()+2));
        worldName.setText("My World");

        worldSize.setForeground(new Color(51, 51, 51));
        worldSize.setText("1000 GB");

        gamemode.setForeground(new Color(51, 51, 51));
        gamemode.setText("Creative");

        lastPlayed.setForeground(new Color(51, 51, 51));
        lastPlayed.setText("12/16/16");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(worldName)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(worldSize)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gamemode)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lastPlayed))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(worldName)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(worldSize)
                    .addComponent(gamemode)
                    .addComponent(lastPlayed))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel gamemode;
    private JLabel lastPlayed;
    private JLabel worldName;
    private JLabel worldSize;
    // End of variables declaration//GEN-END:variables
}
