/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jocopa3.blocktopographpc.gui.nbt;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;

/**
 *
 * @author Matt
 */
public class NBTCell extends javax.swing.JPanel {

    private boolean isValueVisible = true;

    /**
     * Creates new form NBTCell
     */
    public NBTCell() {
        initComponents();
        
        setOpaque(false);
        nameLabel.setOpaque(false);
        valueLabel.setOpaque(false);
        separatorLabel.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new JLabel();
        separatorLabel = new JLabel();
        valueLabel = new JLabel();

        nameLabel.setFont(nameLabel.getFont().deriveFont(nameLabel.getFont().getStyle() | Font.BOLD));
        nameLabel.setText("Name");

        separatorLabel.setText(":");

        valueLabel.setText("Value");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(nameLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueLabel)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(nameLabel)
                .addComponent(separatorLabel)
                .addComponent(valueLabel))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setIcon(ImageIcon icon) {
        if (icon != null) {
            nameLabel.setIcon(icon);
            nameLabel.setIconTextGap(5);
        }
    }

    public void setTagName(String tag) {
        nameLabel.setText(tag);
    }

    public void setTagValue(String tag) {
        valueLabel.setText(tag);
    }
    
    public void setAdditionalInfo(String info) {
        valueLabel.setText(valueLabel.getText() + " " + info);
        isValueVisible = true;
    }

    public void shouldShowValue(boolean show) {
        valueLabel.setVisible(show);
        separatorLabel.setVisible(show);

        isValueVisible = show;
    }

    public boolean isShowingValue() {
        return isValueVisible;
    }

    @Override
    public Font getFont() {
        if (valueLabel == null) {
            return null;
        }

        return valueLabel.getFont();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel nameLabel;
    private JLabel separatorLabel;
    private JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
