/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jocopa3.blocktopographpc.gui.nbt;

import java.awt.Font;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;

/**
 *
 * @author Matt
 */
public class NBTCellt extends javax.swing.JPanel {

    boolean isValueVisible = false;
    
    /**
     * Creates new form NBTCell
     */
    public NBTCellt() {
        initComponents();
        
        nameLabel.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                ((JTextField)e.getComponent()).setBorder(UIManager.getBorder("TextPane.border"));
            }

            @Override
            public void focusLost(FocusEvent e) {
                ((JTextField)e.getComponent()).setBorder(BorderFactory.createEmptyBorder());
            }
        });
        
        valueLabel.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                ((JTextField)e.getComponent()).setBorder(UIManager.getBorder("TextPane.border"));
            }

            @Override
            public void focusLost(FocusEvent e) {
                ((JTextField)e.getComponent()).setBorder(BorderFactory.createEmptyBorder());
            }
        });
        
        setOpaque(false);
        nameLabel.setOpaque(false);
        valueLabel.setOpaque(false);
        separatorLabel.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new JTextField();
        valueLabel = new JTextField();
        separatorLabel = new JLabel();
        iconLabel = new JLabel();

        nameLabel.setBackground(null);
        nameLabel.setText("jTextField1");
        nameLabel.setBorder(BorderFactory.createEmptyBorder());

        valueLabel.setBackground(null);
        valueLabel.setText("jTextField2");
        valueLabel.setBorder(BorderFactory.createEmptyBorder());

        separatorLabel.setText(":");

        iconLabel.setIcon(new ImageIcon(getClass().getResource("/assets/nbt_icons/ic_tag_byte.png"))); // NOI18N
        iconLabel.setIconTextGap(0);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iconLabel, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(separatorLabel)
                    .addComponent(iconLabel, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setIcon(ImageIcon icon) {
        if (icon != null) {
            iconLabel.setIcon(icon);
            //iconLabel.setIconTextGap(5);
        }
    }

    public void setTagName(String tag) {
        nameLabel.setText(tag);
    }

    public void setTagValue(String tag) {
        valueLabel.setText(tag);
    }

    public void shouldShowValue(boolean show) {
        valueLabel.setVisible(show);
        separatorLabel.setVisible(show);

        isValueVisible = show;
    }

    public boolean isShowingValue() {
        return isValueVisible;
    }

    @Override
    public Font getFont() {
        if (valueLabel == null) {
            return null;
        }

        return valueLabel.getFont();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel iconLabel;
    private JTextField nameLabel;
    private JLabel separatorLabel;
    private JTextField valueLabel;
    // End of variables declaration//GEN-END:variables
}
